FROM maven:3.9.11-eclipse-temurin-21-noble

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y git

RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/Vet-Up/banco-back.git
WORKDIR /opt/app/bank-back
RUN git switch -c develop origin/develop
RUN mvn clean install -DskipTests


RUN mvn clean package spring-boot:repackage -Dmaven.test.skip=true

EXPOSE 8080

CMD ["java","-jar", "target/tienda_back-1.0-SNAPSHOT.jar"]