FROM node:22.19.0 AS build

RUN apt-get update
RUN apt-get install -y git

RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/Vet-Up/tienda-front-adm.git
WORKDIR /opt/app/tienda-front-adm
RUN git switch -c release origin/release
RUN npm ci
RUN npm run build



FROM nginx:1.28.0-alpine3.21
COPY --from=build /opt/app/tienda-front-adm/dist/tienda-front-adm/browser/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]