FROM maven:3.9.11-eclipse-temurin-21-noble

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y git

RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/Vet-Up/tienda-back.git
WORKDIR /opt/app/tienda-back
RUN git switch -c release origin/release
RUN mvn clean install -DskipTests

EXPOSE 8081

CMD ["java","-jar", "target/tienda-back-1.0-SNAPSHOT.jar"]